apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: gcr.io/msds-mlops-2025/reddit-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080